apiVersion: ediri.io/minectl/v1alpha1
kind: MinecraftServer
metadata:
  name: minecraft-server
spec:
  cloud: "do"
  region: "fra1"
  size: "s-4vcpu-8gb"
  volumeSize: 100
  ssh: "/Users/dirien/Tools/repos/stackit-minecraft/minecraft/ssh/minecraft.pub"
